MohammadHHaj/Gruppe3-Projektopgave

Forside/styles.css

Har rettet nogle fylde ting ved scrollbaren samt skrevet nogle nøglenoter

Retteltser med scroll bar

---

frontend/index.html
frontend/styles.css

jeg har ændret på placeringen og ændret på breden samt gap på year-wheel

Jeg har lavet de anden sidste ændringer til year-wheel

---

frontend/Kanin.js

Udelukkende tilføjet noter til kanin.js

Jeg har tilføjet noter til kanin.js

---

frontend/Kanin.js
frontend/index.html
frontend/styles.css

Jeg skal sove nu. tak for idag.

Jeg har arbejdet på year-wheel. jeg er træt.

---

frontend/Kanin.js
frontend/script.js
frontend/styles.css

Jeg har lavet mange ændringer i yearwheel - ikke færdigt.

Jeg har lavet ændringer til year-wheel - ikke færdigt.

---

frontend/Kanin.js

kun arb i kanin. Fikset nogle console.logs(samt kommentar)

Kommentar og fikset nogle console.logs(mikkelsideer)

---

frontend/Kanin.js

jeg har gjort sådan at den starter ud med at vælge 1990, men det virker ikke sådan rigtigt

---

frontend/Kanin.js
frontend/index.html
frontend/script.js
frontend/styles.css

jeg har finpudset en masse og tilføjet lidt sejt.

jeg har lavet en masse ændringer og finpudset

---

frontend/index.html
frontend/styles.css

Jeg har tilføjet knapperne til grafen

---

frontend/index.html
frontend/styles.css

fixed top bar til siden

---

frontend/Kanin.js
frontend/index.html
frontend/styles.css

Jeg har fikset kanin så den har fået flotte hvide ører

Jeg har fikset kanin og lavet cursor pointer

---

frontend/index.html
frontend/styles.css

jeg har fikset html og css og kanin

---

frontend/index.html
frontend/styles.css

lille bitte ændring

---

frontend/graf.js
frontend/index.html
frontend/styles.css

Jeg har ryddet lidt op over det hele og lavet fungerende knapper til grafen. Se konsollen..

Jeg har ryddet lidt op over det hele.

---

frontend/styles.css

Jeg har sadt det i midten

---

frontend/styles.css

Fikset year-wheel lidt

---

frontend/Kanin.js
frontend/index.html
frontend/styles.css

Givet knapperne til top-menuen funktioner og tilpasset grafen dertil

Fikset lidt og added funktioner til knapperne i top-menuen

---

frontend/graf.js
frontend/index.html
frontend/styles.css

Tilføjet grafen, men den virker ikke. OVERHOVEDET! ;(

---

Backend/server.js
frontend/graf.js
frontend/index.html
frontend/styles.css

Søgefelt til graf

---

frontend/index.html
frontend/styles.css

Alt tekst er ensrettet med billeder

Alt tekst er ensrettet med billeder

---

frontend/Kanin.js

Oversigtsknappen virker nu

---

frontend/index.html
frontend/styles.css

flyttet tingene

---

frontend/index.html

Tilføjet fade animationer

---

frontend/Sektion1.css

Hovereffect

---

frontend/Sektion1.css
frontend/Sektion4.css
frontend/index.html

Ændringer i sektion1 og 4 og html

---

frontend/Sektion1.css
frontend/Sektion2.css
frontend/Sektion3.css
frontend/index.html
frontend/script.js

Jeg har lavet om i sektion3

---

frontend/Kanin.js
frontend/Sektion1.css

små ting vi kan ændre, klar til feedback torsdag.
